
dist: trusty

group: edge

language: java

sudo: required

jdk: openjdk8

cache:
  directories:
    - $HOME/.m2
script:
  - docker run -it --rm --name my-maven-project -v "$PWD":/usr/src/mymaven/  -w /usr/src/mymaven/ maven:3.3-jdk-8 mvn clean install
