dist: trusty

group: edge

language: java

sudo: required

jdk: openjdk8

notifications:
  email:
    recipients:
      - nicola.bertazzo@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

cache:
  directories:
    - $HOME/.m2
script:
  - export MAVEN_HOME=`mvn --version | grep 'Maven home' | sed -e 's/Maven h.* //'`
  - mvn clean install
